### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rtsisyk** [openshift/machine-config-operator#2287]
**Description**

**Steps to reproduce the issue:**

I installed OKD 4.6.0-0.okd-2020-11-27-200126 on bare metal

**Describe the results you received:**

```
I1204 07:52:12.488276   85913 daemon.go:1082] Validating against pending config rendered-master-d5b9190dac5cb0c9e2119d361
58e1ba2                                                                                                                  
E1204 07:52:12.493942   85913 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runti
me error: invalid memory address or nil pointer dereference)                                                          
goroutine 91 [running]:                                                                                                  
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19c6fc0, 0x2a0efd0)                         
        /go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0
xa6                                                                                                                      
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)                             
        /go/src/github.com/openshift/machine-config-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0
x89
panic(0x19c6fc0, 0x2a0efd0)
        /usr/lib/golang/src/runtime/panic.go:969 +0x175
github.com/openshift/machine-config-operator/pkg/daemon.checkV3Files(0xc000247000, 0x1b, 0x1c, 0x1ada6c0, 0xc00090a300)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:1453 +0x118
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).validateOnDiskState(0xc0000e8580, 0xc00030beb8, 0x0, 0x
0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:1332 +0x3de
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).checkStateOnFirstRun(0xc0000e8580, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:1090 +0x3e9
github.com/openshift/machine-config-operator/pkg/daemon.(*Daemon).syncNode(0xc0000e8580, 0xc00080ee90, 0x8, 0x0, 0x0)
        /go/src/github.com/openshift/machine-config-operator/pkg/daemon/daemon.go:460 +0x3da
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `oc adm release info --commits | grep machine-config-operator`:**

```
  machine-config-operator                        https://github.com/openshift/machine-config-operator                        5a9e6b4eedaf72ecc2534355173843e011f19765
```

**Additional environment details (platform, options, etc.):**

[crash.log](https://github.com/openshift/machine-config-operator/files/5641230/crash.log)
[rendered-master-d5b9190dac5cb0c9e2119d36158e1ba2.yaml.gz](https://github.com/openshift/machine-config-operator/files/5641259/rendered-master-d5b9190dac5cb0c9e2119d36158e1ba2.yaml.gz)

**Comment by rtsisyk** [comment]
I found the root case. My manifests had duplicated `users:` entry. As result, MCO failed to generate renedered-master manifest.
Anyway, please add a proper check for nil-value to the Go code.
