### ISSUE TITLE
ci failures: bootkube.sh: Invalid character(s) found in major number "machine-config-daemon-4"

### ISSUE THREAD

**Issue by kikisdeliveryservice** [openshift/machine-config-operator#976]
**Description**
Seeing a pattern of bootkube.sh CI failures beginning around 4 hours ago.

**Steps to reproduce the issue:**
1. looking at e2e ci runs that fail around ~45-5x minutes with exit code 1
2. lookign at log-bundle-xxx.tar -> /bootstrap/journals/bootkube.log

**Describe the results you received:**
```
Jul 16 21:23:18 ip-10-0-11-239 systemd[1]: Started Bootstrap a Kubernetes cluster.
Jul 16 21:23:19 ip-10-0-11-239 podman[7844]: 2019-07-16 21:23:19.784564535 +0000 UTC m=+0.315776402 container create aec1e9a6654e8c8f562654b97d95329152b57635a5853e86fef6c1833dbd7cba (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=nostalgic_neumann)
Jul 16 21:23:20 ip-10-0-11-239 podman[7844]: 2019-07-16 21:23:20.461016745 +0000 UTC m=+0.992228687 container init aec1e9a6654e8c8f562654b97d95329152b57635a5853e86fef6c1833dbd7cba (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=nostalgic_neumann)
Jul 16 21:23:20 ip-10-0-11-239 podman[7844]: 2019-07-16 21:23:20.47647134 +0000 UTC m=+1.007683402 container start aec1e9a6654e8c8f562654b97d95329152b57635a5853e86fef6c1833dbd7cba (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=nostalgic_neumann)
...
Jul 16 21:23:24 ip-10-0-11-239 podman[8142]: 2019-07-16 21:23:24.573127361 +0000 UTC m=+1.064963057 container start b9770016665157f967082473053a543866d04e946f0d54be202ce050afe63042 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=peaceful_neumann)
Jul 16 21:23:24 ip-10-0-11-239 podman[8142]: 2019-07-16 21:23:24.573502682 +0000 UTC m=+1.065338444 container attach b9770016665157f967082473053a543866d04e946f0d54be202ce050afe63042 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=peaceful_neumann)
Jul 16 21:23:25 ip-10-0-11-239 podman[8295]: 2019-07-16 21:23:25.850445414 +0000 UTC m=+0.280537633 container create 609adb835aed9e197bf6ba730021e0218d059d648a53b7e09c2de880df441dc4 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=lucid_mendel)
Jul 16 21:23:26 ip-10-0-11-239 podman[8295]: 2019-07-16 21:23:26.529653079 +0000 UTC m=+0.959745396 container init 609adb835aed9e197bf6ba730021e0218d059d648a53b7e09c2de880df441dc4 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=lucid_mendel)
Jul 16 21:23:26 ip-10-0-11-239 podman[8295]: 2019-07-16 21:23:26.545217694 +0000 UTC m=+0.975310107 container start 609adb835aed9e197bf6ba730021e0218d059d648a53b7e09c2de880df441dc4 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=lucid_mendel)
Jul 16 21:23:26 ip-10-0-11-239 podman[8295]: 2019-07-16 21:23:26.545323756 +0000 UTC m=+0.975416069 container attach 609adb835aed9e197bf6ba730021e0218d059d648a53b7e09c2de880df441dc4 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=lucid_mendel)
Jul 16 21:23:27 ip-10-0-11-239 podman[8454]: 2019-07-16 21:23:27.941397255 +0000 UTC m=+0.282984337 container create 0cbc009ad13384e081494a409fc1b4057dc52fb204a29f83ff2401b3567d1877 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=crazy_dijkstra)
Jul 16 21:23:28 ip-10-0-11-239 podman[8454]: 2019-07-16 21:23:28.594463336 +0000 UTC m=+0.936050452 container init 0cbc009ad13384e081494a409fc1b4057dc52fb204a29f83ff2401b3567d1877 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=crazy_dijkstra)
Jul 16 21:23:28 ip-10-0-11-239 podman[8454]: 2019-07-16 21:23:28.609857278 +0000 UTC m=+0.951444509 container start 0cbc009ad13384e081494a409fc1b4057dc52fb204a29f83ff2401b3567d1877 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=crazy_dijkstra)
Jul 16 21:23:28 ip-10-0-11-239 podman[8454]: 2019-07-16 21:23:28.610248802 +0000 UTC m=+0.951836145 container attach 0cbc009ad13384e081494a409fc1b4057dc52fb204a29f83ff2401b3567d1877 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=crazy_dijkstra)
Jul 16 21:23:29 ip-10-0-11-239 podman[8613]: 2019-07-16 21:23:29.968492139 +0000 UTC m=+0.265323378 container create 81315423f90377273a1ff3ef7d9cc6bf6d16a0deb0c4cc3fa5cdd8c2829cf043 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=keen_agnesi)
Jul 16 21:23:30 ip-10-0-11-239 podman[8613]: 2019-07-16 21:23:30.631029699 +0000 UTC m=+0.927861071 container init 81315423f90377273a1ff3ef7d9cc6bf6d16a0deb0c4cc3fa5cdd8c2829cf043 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=keen_agnesi)
Jul 16 21:23:30 ip-10-0-11-239 podman[8613]: 2019-07-16 21:23:30.644688014 +0000 UTC m=+0.941519378 container start 81315423f90377273a1ff3ef7d9cc6bf6d16a0deb0c4cc3fa5cdd8c2829cf043 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=keen_agnesi)
Jul 16 21:23:30 ip-10-0-11-239 podman[8613]: 2019-07-16 21:23:30.64544985 +0000 UTC m=+0.942281433 container attach 81315423f90377273a1ff3ef7d9cc6bf6d16a0deb0c4cc3fa5cdd8c2829cf043 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=keen_agnesi)
Jul 16 21:23:31 ip-10-0-11-239 podman[8758]: 2019-07-16 21:23:31.930335332 +0000 UTC m=+0.280189376 container create 7dd3bc0358d684cee6a8a8e2f1f123f983c257a208c10e9250293c035fc797aa (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=laughing_taussig)
Jul 16 21:23:32 ip-10-0-11-239 podman[8758]: 2019-07-16 21:23:32.630615076 +0000 UTC m=+0.980469087 container init 7dd3bc0358d684cee6a8a8e2f1f123f983c257a208c10e9250293c035fc797aa (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=laughing_taussig)
Jul 16 21:23:32 ip-10-0-11-239 podman[8758]: 2019-07-16 21:23:32.646603267 +0000 UTC m=+0.996457587 container start 7dd3bc0358d684cee6a8a8e2f1f123f983c257a208c10e9250293c035fc797aa (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=laughing_taussig)
Jul 16 21:23:32 ip-10-0-11-239 podman[8758]: 2019-07-16 21:23:32.646718269 +0000 UTC m=+0.996572355 container attach 7dd3bc0358d684cee6a8a8e2f1f123f983c257a208c10e9250293c035fc797aa (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=laughing_taussig)
...
Jul 16 21:23:34 ip-10-0-11-239 podman[8914]: 2019-07-16 21:23:34.87363454 +0000 UTC m=+1.083441691 container start f787ecbc81a68cf11d3cc361f2ae94dfbf5483777f4d6d64740797955477df51 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=modest_wozniak)
Jul 16 21:23:34 ip-10-0-11-239 podman[8914]: 2019-07-16 21:23:34.873787783 +0000 UTC m=+1.083595044 container attach f787ecbc81a68cf11d3cc361f2ae94dfbf5483777f4d6d64740797955477df51 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=modest_wozniak)
Jul 16 21:23:36 ip-10-0-11-239 podman[9071]: 2019-07-16 21:23:36.152203668 +0000 UTC m=+0.267328498 container create 7443da8bc73843ba9ed5d3e98e05e847d6914ebe972d0eb7f50cc3a597b810b1 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=suspicious_banzai)
Jul 16 21:23:36 ip-10-0-11-239 podman[9071]: 2019-07-16 21:23:36.826943075 +0000 UTC m=+0.942068051 container init 7443da8bc73843ba9ed5d3e98e05e847d6914ebe972d0eb7f50cc3a597b810b1 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=suspicious_banzai)
...
Jul 16 21:23:38 ip-10-0-11-239 podman[9216]: 2019-07-16 21:23:38.116055596 +0000 UTC m=+0.279658052 container create d3c5069f942c03a93ed7f7d4dbb446437c12b844b55fcf5ed3b0c064f456fdbd (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=cranky_antonelli)
Jul 16 21:23:38 ip-10-0-11-239 podman[9216]: 2019-07-16 21:23:38.763899298 +0000 UTC m=+0.927501799 container init d3c5069f942c03a93ed7f7d4dbb446437c12b844b55fcf5ed3b0c064f456fdbd (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=cranky_antonelli)
Jul 16 21:23:38 ip-10-0-11-239 podman[9216]: 2019-07-16 21:23:38.777840083 +0000 UTC m=+0.941442668 container start d3c5069f942c03a93ed7f7d4dbb446437c12b844b55fcf5ed3b0c064f456fdbd (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=cranky_antonelli)
Jul 16 21:23:38 ip-10-0-11-239 podman[9216]: 2019-07-16 21:23:38.777969016 +0000 UTC m=+0.941571543 container attach d3c5069f942c03a93ed7f7d4dbb446437c12b844b55fcf5ed3b0c064f456fdbd (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=cranky_antonelli)
Jul 16 21:23:40 ip-10-0-11-239 podman[9367]: 2019-07-16 21:23:40.178715205 +0000 UTC m=+0.289996979 container create b54962f2ef43ccbe042a56edf798305481408e0aae25c5c7f17f4eda36a1e81a (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=upbeat_jackson)
...
Jul 16 21:23:44 ip-10-0-11-239 podman[9661]: 2019-07-16 21:23:44.923542099 +0000 UTC m=+0.915146890 container init 7cf0d9e7e319c56ee6bba8d50c872ec030663c9cceed94264ea9b45990a12444 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=happy_dubinsky)
Jul 16 21:23:44 ip-10-0-11-239 podman[9661]: 2019-07-16 21:23:44.948112526 +0000 UTC m=+0.939717316 container start 7cf0d9e7e319c56ee6bba8d50c872ec030663c9cceed94264ea9b45990a12444 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=happy_dubinsky)
Jul 16 21:23:44 ip-10-0-11-239 podman[9661]: 2019-07-16 21:23:44.94823707 +0000 UTC m=+0.939841985 container attach 7cf0d9e7e319c56ee6bba8d50c872ec030663c9cceed94264ea9b45990a12444 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/release@sha256:0e56f818093ef4777a5e187b91375fb98d2b9b8952e118e59c5e0b093ae4eb95, name=happy_dubinsky)
Jul 16 21:23:46 ip-10-0-11-239 bootkube.sh[7809]: Rendering MCO manifests...
Jul 16 21:23:46 ip-10-0-11-239 podman[9857]: 2019-07-16 21:23:46.948410359 +0000 UTC m=+0.265035014 container create 2881a382d17a0b8bf6d9bf066dd22b00a445bff5b7f8332c6ed2178fb2559689 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/stable@sha256:64fe65e384a773ea9fd829b8a12339923c753c7d378555481d8b4195123a348d, name=priceless_elion)
Jul 16 21:23:47 ip-10-0-11-239 podman[9857]: 2019-07-16 21:23:47.672249546 +0000 UTC m=+0.988874382 container init 2881a382d17a0b8bf6d9bf066dd22b00a445bff5b7f8332c6ed2178fb2559689 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/stable@sha256:64fe65e384a773ea9fd829b8a12339923c753c7d378555481d8b4195123a348d, name=priceless_elion)
Jul 16 21:23:47 ip-10-0-11-239 podman[9857]: 2019-07-16 21:23:47.688383279 +0000 UTC m=+1.005008065 container start 2881a382d17a0b8bf6d9bf066dd22b00a445bff5b7f8332c6ed2178fb2559689 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/stable@sha256:64fe65e384a773ea9fd829b8a12339923c753c7d378555481d8b4195123a348d, name=priceless_elion)
Jul 16 21:23:47 ip-10-0-11-239 podman[9857]: 2019-07-16 21:23:47.688749233 +0000 UTC m=+1.005374056 container attach 2881a382d17a0b8bf6d9bf066dd22b00a445bff5b7f8332c6ed2178fb2559689 (image=registry.svc.ci.openshift.org/ci-op-9n865rsi/stable@sha256:64fe65e384a773ea9fd829b8a12339923c753c7d378555481d8b4195123a348d, name=priceless_elion)
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: panic: semver: Parse(machine-config-daemon-4.2.0-201907161330-2-g55ce6ae2-dirty): Invalid character(s) found in major number "machine-config-daemon-4"
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: goroutine 1 [running]:
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: github.com/openshift/machine-config-operator/vendor/github.com/blang/semver.MustParse(0x177cac0, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]:         /go/src/github.com/openshift/machine-config-operator/vendor/github.com/blang/semver/semver.go:356 +0x1c1
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: github.com/openshift/machine-config-operator/pkg/version.init.ializers()
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]:         /go/src/github.com/openshift/machine-config-operator/pkg/version/version.go:19 +0x78
Jul 16 21:23:48 ip-10-0-11-239 systemd[1]: bootkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jul 16 21:23:48 ip-10-0-11-239 systemd[1]: bootkube.service: Failed with result 'exit-code'.
Jul 16 21:23:53 ip-10-0-11-239 systemd[1]: bootkube.service: Service RestartSec=5s expired, scheduling restart.
Jul 16 21:23:53 ip-10-0-11-239 systemd[1]: bootkube.service: Scheduled restart job, restart counter is at 63.
Jul 16 21:23:53 ip-10-0-11-239 systemd[1]: Stopped Bootstrap a Kubernetes cluster.

```

Key part of above logs:
```
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: panic: semver: Parse(machine-config-daemon-4.2.0-201907161330-2-g55ce6ae2-dirty): Invalid character(s) found in major number "machine-config-daemon-4"
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: goroutine 1 [running]:
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: github.com/openshift/machine-config-operator/vendor/github.com/blang/semver.MustParse(0x177cac0, 0x3a, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]:         /go/src/github.com/openshift/machine-config-operator/vendor/github.com/blang/semver/semver.go:356 +0x1c1
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]: github.com/openshift/machine-config-operator/pkg/version.init.ializers()
Jul 16 21:23:47 ip-10-0-11-239 bootkube.sh[7809]:         /go/src/github.com/openshift/machine-config-operator/pkg/version/version.go:19 +0x78
Jul 16 21:23:48 ip-10-0-11-239 systemd[1]: bootkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
**Describe the results you expected:**

I dont expect to see this error at all

Example runs:
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/894/pull-ci-openshift-machine-config-operator-master-e2e-aws/4534/artifacts/e2e-aws/installer/
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/926/pull-ci-openshift-machine-config-operator-master-e2e-aws/4532/artifacts/e2e-aws/installer/
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/972/pull-ci-openshift-machine-config-operator-master-e2e-aws/4537/artifacts/e2e-aws/installer/
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/926/pull-ci-openshift-machine-config-operator-master-e2e-aws/4538/artifacts/e2e-aws/installer/
https://gcsweb-ci.svc.ci.openshift.org/gcs/origin-ci-test/pr-logs/pull/openshift_machine-config-operator/971/pull-ci-openshift-machine-config-operator-master-e2e-aws/4535/artifacts/e2e-aws/installer/

**Comment by cgwalters** [comment]
I haven't dug into this fully but I think this may be a change in ART...maybe even fallout from the ART side of the uni-image?

**Comment by cgwalters** [comment]
That said, also as a result of the uni-image, I don't think we need to be parsing our own version number anymore.

**Comment by cgwalters** [comment]
Yeah, looks like what happened is that we have a new git tag in our upstream repo:

```
git show machine-config-daemon-4.2.0-201907161330
tag machine-config-daemon-4.2.0-201907161330
Tagger:     AOS Automation Release Team <aos-team-art@redhat.com>
TaggerDate: Tue Jul 16 13:30:24 2019 -0400

Release with doozer

commit 962919766af39d279bd4226be6790ac04bd76ab2 (HEAD -> master, tag: machine-config-daemon-4.2.0-201907161330, origin/release-4.3, origin/release-4.2, origin/master, origin/HEAD)
Merge: 3e6681a4 49abfe65
Author:     OpenShift Merge Robot <openshift-merge-robot@users.noreply.github.com>
AuthorDate: Tue Jul 16 18:01:28 2019 +0200
Commit:     GitHub <noreply@github.com>
CommitDate: Tue Jul 16 18:01:28 2019 +0200

    Merge pull request #970 from cgwalters/make-deploy-fixes
    
    hack/cluster-push: Fix for single image

```

**Comment by cgwalters** [comment]
Probably this doesn't break any other component because they aren't parsing their own version.  So we should stop doing that too.

**Comment by cgwalters** [comment]
To clarify, ART pushing the git tag broke us, notice the difference here:

```
walters@toolbox /s/w/s/g/o/machine-config-operator> git rev-parse HEAD
962919766af39d279bd4226be6790ac04bd76ab2
walters@toolbox /s/w/s/g/o/machine-config-operator> git describe --tags --always
machine-config-daemon-4.2.0-201907161330
walters@toolbox /s/w/s/g/o/machine-config-operator> git describe --tags --always HEAD^
v4.2.0-alpha.0-64-g3e6681a4
walters@toolbox /s/w/s/g/o/machine-config-operator> 
```

**Comment by kikisdeliveryservice** [comment]
I'm a little confused why we have that tag in our repo? it _is_ from the cluster-push.sh?

**Comment by cgwalters** [comment]
Nah, ART just pushed a git tag at that time.

**Comment by cgwalters** [comment]
I'm working on a patch.

**Comment by kikisdeliveryservice** [comment]
Awesome, thanks @cgwalters !!!

**Comment by cgwalters** [comment]
PR in https://github.com/openshift/machine-config-operator/pull/977
